#ifndef CATALOGS_TRITONPREFS_H
#define CATALOGS_TRITONPREFS_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_MAIN_PROJECT_MENU 0
#define MSG_MAIN_PROJECT_REMOVE 1
#define MSG_MAIN_PROJECT_ABOUT 2
#define MSG_MAIN_PROJECT_QUIT 3
#define MSG_MAIN_EDIT_MENU 4
#define MSG_MAIN_EDIT_DEFAULTS 5
#define MSG_MAIN_EDIT_LASTSAVED 6
#define MSG_MAIN_EDIT_RESTORE 7
#define MSG_MAIN_EDIT_GLOBAL 8
#define MSG_MAIN_APPLICATIONS_GADGET 9
#define MSG_MAIN_INFO_GADGET 10
#define MSG_MAIN_DELETE_GADGET 11
#define MSG_MAIN_FRAMES_GADGET 12
#define MSG_MAIN_PENS_GADGET 13
#define MSG_MAIN_IMAGES_GADGET 14
#define MSG_MAIN_WINDOWS_GADGET 15
#define MSG_MAIN_SYSTEM_GADGET 16
#define MSG_MAIN_SAVE_GADGET 17
#define MSG_MAIN_USE_GADGET 18
#define MSG_MAIN_TEST_GADGET 19
#define MSG_FRAMES_WIDTH_GADGET 20
#define MSG_FRAMES_TITLE_GADGET 21
#define MSG_FRAMES_FRAMETYPES_TEXT 22
#define MSG_FRAMES_KIND_BUTTON_GADGET 23
#define MSG_FRAMES_KIND_FRAMEBOX_GADGET 24
#define MSG_FRAMES_KIND_GROUPBOX_GADGET 25
#define MSG_FRAMES_KIND_PROGRESS_GADGET 26
#define MSG_FRAMES_KIND_ICONDROPBOX_GADGET 27
#define MSG_WINDOWS_WINDOWS_GADGET 28
#define MSG_SYSTEM_PUBSCREENS_GADGET 29
#define MSG_WINDOWS_INFO_GADGET 30
#define MSG_WINDOWS_SNAPSHOT_GADGET 31
#define MSG_WINDOWS_UNSNAPSHOT_GADGET 32
#define MSG_WINDOWS_SNAPSHOTALL_GADGET 33
#define MSG_WINDOWS_UNSNAPSHOTALL_GADGET 34
#define MSG_SYSTEM_ADD_GADGET 35
#define MSG_SYSTEM_DELETE_GADGET 36
#define MSG_SYSTEM_EDIT_GADGET 37
#define MSG_SYSTEM_TEST_GADGET 38
#define MSG_SYSTEM_USE_GADGET 39
#define MSG_SYSTEM_MISC_LABEL 40
#define MSG_SYSTEM_SIMPLEREFRESH_CHECKBOX 41
#define MSG_SCREEN_INFOLINE 42
#define MSG_SCREEN_SCREENMODE_GADGET 43
#define MSG_SCREEN_PUBLICNAME_GADGET 44
#define MSG_SCREEN_SCREENTITLE_GADGET 45
#define MSG_PENS_TYPE_GADGET 46
#define MSG_IMAGES_TYPE_GADGET 47
#define MSG_IMAGES_RETURN_CHECKBOX 48
#define MSG_OK_GAD 49
#define MSG_CANCEL_GAD 50
#define MSG_YES_NO_GAD 51
#define MSG_REMOVEIT_ABORT_GAD 52
#define MSG_INSTALLIT_QUIT_GAD 53
#define MSG_MAIN_TITLE 54
#define MSG_FRAMES_TITLE 55
#define MSG_PENS_TITLE 56
#define MSG_IMAGES_TITLE 57
#define MSG_WINDOWS_TITLE 58
#define MSG_SYSTEM_TITLE 59
#define MSG_ERROR_TITLE 60
#define MSG_SCREEN_TITLE 61
#define MSG_TESTSCREEN_TITLE 62
#define MSG_APPINFO_TITLE 63
#define MSG_WININFO_TITLE 64
#define MSG_ABOUT_TITLE 65
#define MSG_PICKSCREENMODE_TITLE 66
#define MSG_APPINFO_REQUESTER 67
#define MSG_REMOVE_REQUESTER 68
#define MSG_WININFO_REQUESTER 69
#define MSG_ABOUT_UNREG 70
#define MSG_ABOUT_REG 71
#define MSG_DELETEAPP_REQUESTER 72
#define MSG_INSTALLPREFS_REQUESTER 73
#define MSG_GLOBALNAME 74
#define MSG_SYSTEMPEN_DETAILPEN 75
#define MSG_SYSTEMPEN_BLOCKPEN 76
#define MSG_SYSTEMPEN_TEXTPEN 77
#define MSG_SYSTEMPEN_SHINEPEN 78
#define MSG_SYSTEMPEN_SHADOWPEN 79
#define MSG_SYSTEMPEN_FILLPEN 80
#define MSG_SYSTEMPEN_FILLTEXTPEN 81
#define MSG_SYSTEMPEN_BACKGROUNDPEN 82
#define MSG_SYSTEMPEN_HIGHLIGHTTEXTPEN 83
#define MSG_IMAGE_WINBACK 84
#define MSG_IMAGE_REQBACK 85
#define MSG_IMAGE_USBUTTONBACK 86
#define MSG_IMAGE_SBUTTONBACK 87
#define MSG_PATTERN_BACKGROUND 88
#define MSG_PATTERN_SHINE 89
#define MSG_PATTERN_SHINE_SHADOW 90
#define MSG_PATTERN_SHINE_FILL 91
#define MSG_PATTERN_SHINE_BACKGROUND 92
#define MSG_PATTERN_SHADOW 93
#define MSG_PATTERN_SHADOW_FILL 94
#define MSG_PATTERN_SHADOW_BACKGROUND 95
#define MSG_PATTERN_FILL 96
#define MSG_PATTERN_FILL_BACKGROUND 97
#define MSG_PENKIND_NORMUSCORE 98
#define MSG_PENKIND_HIGHUSCORE 99
#define MSG_PENKIND_HALFSHINE 100
#define MSG_PENKIND_HALFSHADOW 101
#define MSG_PENKIND_USSTRINGGADBACK 102
#define MSG_PENKIND_SSTRINGGADBACK 103
#define MSG_PENKIND_USSTRINGGADFRONT 104
#define MSG_PENKIND_SSTRINGGADFRONT 105
#define MSG_COLOR_0 106
#define MSG_COLOR_1 107
#define MSG_COLOR_2 108
#define MSG_COLOR_3 109
#define MSG_COLOR_4 110
#define MSG_COLOR_5 111
#define MSG_COLOR_6 112
#define MSG_COLOR_7 113
#define MSG_CYCLE_WIDTH_THICK 114
#define MSG_CYCLE_WIDTH_THIN 115
#define MSG_CYCLE_TITLE_NORMAL 116
#define MSG_CYCLE_TITLE_HIGHLIGHT 117
#define MSG_CYCLE_TITLE_SHADOW 118
#define MSG_CYCLE_RAISED_RECESSED 119
#define MSG_CYCLE_RAISED_RAISED 120
#define MSG_CYCLE_KIND_STANDARD 121
#define MSG_CYCLE_KIND_STRING 122
#define MSG_CYCLE_KIND_ICONDROPBOX 123
#define MSG_CYCLE_KIND_XENBUTTON1 124
#define MSG_CYCLE_KIND_XENBUTTON2 125
#define MSG_CYCLE_KIND_NEXTBUTTON 126
#define MSG_CYCLE_PENTYPE_SYSTEMPEN 127
#define MSG_CYCLE_PENTYPE_PEN 128
#define MSG_CYCLE_PATTERNTYPE_BFPATTERN 129
#define MSG_CYCLE_PATTERNTYPE_PEN 130
#define MSG_ERROR_LOADSETTINGS 131
#define MSG_ERROR_CREATEAPP 132
#define MSG_ERROR_INSTALLTRITON 133
#define MSG_ERROR_MAINWINDOW 134
#define MSG_ERROR_BOOPSIIMAGE 135
#define MSG_ERROR_NOTRITONLIB 136
#define MSG_ERROR_NOMEM 137
#define MSG_ERROR_NOREQTOOLSNOASLLIB 138
#define MSG_ERROR_CHECKSUM 139
#define MSG_TRITON_APP_LONGNAME 140
#define MSG_TRITON_APP_INFO 141
#define MSG_UNNAMEDSCREEN_LABEL 142
#define MSG_PRDEFSCREEN_LABEL 143
#define MSG_DEFSCREEN_LABEL 144
#define MSG_WBSCREEN_LABEL 145

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_MAIN_PROJECT_MENU_STR "Project"
#define MSG_MAIN_PROJECT_REMOVE_STR "X_Remove..."
#define MSG_MAIN_PROJECT_ABOUT_STR "?_About..."
#define MSG_MAIN_PROJECT_QUIT_STR "Q_Quit"
#define MSG_MAIN_EDIT_MENU_STR "Edit"
#define MSG_MAIN_EDIT_DEFAULTS_STR "D_Reset To Defaults"
#define MSG_MAIN_EDIT_LASTSAVED_STR "L_Last Saved"
#define MSG_MAIN_EDIT_RESTORE_STR "R_Restore"
#define MSG_MAIN_EDIT_GLOBAL_STR "G_Reset To Global"
#define MSG_MAIN_APPLICATIONS_GADGET_STR "Applications"
#define MSG_MAIN_INFO_GADGET_STR "_Info"
#define MSG_MAIN_DELETE_GADGET_STR "_Delete"
#define MSG_MAIN_FRAMES_GADGET_STR "_Frames"
#define MSG_MAIN_PENS_GADGET_STR "_Pens"
#define MSG_MAIN_IMAGES_GADGET_STR "I_mages"
#define MSG_MAIN_WINDOWS_GADGET_STR "_Windows"
#define MSG_MAIN_SYSTEM_GADGET_STR "S_ystem"
#define MSG_MAIN_SAVE_GADGET_STR "_Save"
#define MSG_MAIN_USE_GADGET_STR "_Use"
#define MSG_MAIN_TEST_GADGET_STR "_Test"
#define MSG_FRAMES_WIDTH_GADGET_STR "_Width"
#define MSG_FRAMES_TITLE_GADGET_STR "_Title"
#define MSG_FRAMES_FRAMETYPES_TEXT_STR "Frame types"
#define MSG_FRAMES_KIND_BUTTON_GADGET_STR "_Button"
#define MSG_FRAMES_KIND_FRAMEBOX_GADGET_STR "_Framing box"
#define MSG_FRAMES_KIND_GROUPBOX_GADGET_STR "_Grouping box"
#define MSG_FRAMES_KIND_PROGRESS_GADGET_STR "_Progress Indicator"
#define MSG_FRAMES_KIND_ICONDROPBOX_GADGET_STR "_Icon drop box"
#define MSG_WINDOWS_WINDOWS_GADGET_STR "Windows"
#define MSG_SYSTEM_PUBSCREENS_GADGET_STR "Public screens"
#define MSG_WINDOWS_INFO_GADGET_STR "_Info"
#define MSG_WINDOWS_SNAPSHOT_GADGET_STR "_Snapshot"
#define MSG_WINDOWS_UNSNAPSHOT_GADGET_STR "UnSnaps_hot"
#define MSG_WINDOWS_SNAPSHOTALL_GADGET_STR "S_napshot all"
#define MSG_WINDOWS_UNSNAPSHOTALL_GADGET_STR "UnSna_pshot all"
#define MSG_SYSTEM_ADD_GADGET_STR "_Add"
#define MSG_SYSTEM_DELETE_GADGET_STR "_Delete"
#define MSG_SYSTEM_EDIT_GADGET_STR "_Edit"
#define MSG_SYSTEM_TEST_GADGET_STR "_Test"
#define MSG_SYSTEM_USE_GADGET_STR "_Use"
#define MSG_SYSTEM_MISC_LABEL_STR "Miscellaneous"
#define MSG_SYSTEM_SIMPLEREFRESH_CHECKBOX_STR "S_imple refresh"
#define MSG_SCREEN_INFOLINE_STR "%s, %ld colors"
#define MSG_SCREEN_SCREENMODE_GADGET_STR "_Screen mode"
#define MSG_SCREEN_PUBLICNAME_GADGET_STR "_Public name"
#define MSG_SCREEN_SCREENTITLE_GADGET_STR "Screen _title"
#define MSG_PENS_TYPE_GADGET_STR "_Type:"
#define MSG_IMAGES_TYPE_GADGET_STR "_Type:"
#define MSG_IMAGES_RETURN_CHECKBOX_STR "U_se <Return> arrow in buttons"
#define MSG_OK_GAD_STR "_Ok"
#define MSG_CANCEL_GAD_STR "_Cancel"
#define MSG_YES_NO_GAD_STR "_Yes|_No"
#define MSG_REMOVEIT_ABORT_GAD_STR "_Remove it|_Abort"
#define MSG_INSTALLIT_QUIT_GAD_STR "_Install it|_Quit"
#define MSG_MAIN_TITLE_STR "Triton Preferences"
#define MSG_FRAMES_TITLE_STR "Frames"
#define MSG_PENS_TITLE_STR "Pens"
#define MSG_IMAGES_TITLE_STR "Images"
#define MSG_WINDOWS_TITLE_STR "Windows"
#define MSG_SYSTEM_TITLE_STR "System"
#define MSG_ERROR_TITLE_STR "Error"
#define MSG_SCREEN_TITLE_STR "Edit public screen"
#define MSG_TESTSCREEN_TITLE_STR "Close window to continue"
#define MSG_APPINFO_TITLE_STR "Application Info"
#define MSG_WININFO_TITLE_STR "Window Info"
#define MSG_ABOUT_TITLE_STR "About..."
#define MSG_PICKSCREENMODE_TITLE_STR "Select screen mode"
#define MSG_APPINFO_REQUESTER_STR "%%sName:\n%%n%s (%s)\r%%sInformation:\n%%n%s\r%%sVersion:\n%%n%s (Release %s)\r%%sDate:\n%%n%s"
#define MSG_REMOVE_REQUESTER_STR "This operation will remove the\n%sTriton Preferences System\n%nfrom your computer, including\nall application information and\nuser settings!\rThe drawers\n%senv:Triton\n%nand\n%senvarc:Triton\n%nand their contents will be deleted!\t%sDo you want to remove the\nTriton Preferences System?"
#define MSG_WININFO_REQUESTER_STR "%%sName:\n%%n%s\r%%sID:\n%%n%ld\r%%sDimensions:\n%%n%ld/%ld/%ld/%ld\r%%sAlternate dimensions:\n%%n%ld/%ld/%ld/%ld"
#define MSG_ABOUT_UNREG_STR "%%sTriton Preferences %s (%s)\n%%n©1994-1995 by Stefan Zeiger\rCompilation date: %s\t%%hUnregistered version\n(Only system preferences can be saved)\t%%nTo register, send US$15/DM20 to\r%%hStefan Zeiger\nSeligenstädter Weg 24\n63796 Kahl\nGermany\t%%nSee documentation for details."
#define MSG_ABOUT_REG_STR "%%sTriton Preferences %s (%s)\n%%n©1994-1995 by Stefan Zeiger\rCompilation date: %s\t%%nThis version is registered to\r%%h%s\r%%n(Serial no. %s)\t%%nThanks for your support!"
#define MSG_DELETEAPP_REQUESTER_STR "All settings of the application\n%%s%s (%s)\n%%nwill be lost.\rAre you sure you want to delete it?"
#define MSG_INSTALLPREFS_REQUESTER_STR "The Triton Preferences System is not yet installed.\nIf you choose to install it, the drawers\n%senv:Triton\n%nand\n%senvarc:Triton\n%nwill be created. Triton applications will then save\ntheir preferences into these drawers.\t%sDo you want to install the Triton Preferences System?"
#define MSG_GLOBALNAME_STR "«Global»"
#define MSG_SYSTEMPEN_DETAILPEN_STR "Detail pen"
#define MSG_SYSTEMPEN_BLOCKPEN_STR "Block pen"
#define MSG_SYSTEMPEN_TEXTPEN_STR "Text pen"
#define MSG_SYSTEMPEN_SHINEPEN_STR "Shine pen"
#define MSG_SYSTEMPEN_SHADOWPEN_STR "Shadow pen"
#define MSG_SYSTEMPEN_FILLPEN_STR "Fill pen"
#define MSG_SYSTEMPEN_FILLTEXTPEN_STR "Fill text pen"
#define MSG_SYSTEMPEN_BACKGROUNDPEN_STR "Background pen"
#define MSG_SYSTEMPEN_HIGHLIGHTTEXTPEN_STR "Highlight text pen"
#define MSG_IMAGE_WINBACK_STR "BG Window"
#define MSG_IMAGE_REQBACK_STR "BG Requester"
#define MSG_IMAGE_USBUTTONBACK_STR "BG Unselected button"
#define MSG_IMAGE_SBUTTONBACK_STR "BG Selected button"
#define MSG_PATTERN_BACKGROUND_STR "Background"
#define MSG_PATTERN_SHINE_STR "Shine"
#define MSG_PATTERN_SHINE_SHADOW_STR "Shine/Shadow"
#define MSG_PATTERN_SHINE_FILL_STR "Shine/Fill"
#define MSG_PATTERN_SHINE_BACKGROUND_STR "Shine/Background"
#define MSG_PATTERN_SHADOW_STR "Shadow"
#define MSG_PATTERN_SHADOW_FILL_STR "Shadow/Fill"
#define MSG_PATTERN_SHADOW_BACKGROUND_STR "Shadow/Background"
#define MSG_PATTERN_FILL_STR "Fill"
#define MSG_PATTERN_FILL_BACKGROUND_STR "Fill/Background"
#define MSG_PENKIND_NORMUSCORE_STR "Underscore"
#define MSG_PENKIND_HIGHUSCORE_STR "Highlighted underscore"
#define MSG_PENKIND_HALFSHINE_STR "Halfshine"
#define MSG_PENKIND_HALFSHADOW_STR "Halfshadow"
#define MSG_PENKIND_USSTRINGGADBACK_STR "BG Unselected string gadget"
#define MSG_PENKIND_SSTRINGGADBACK_STR "BG Selected string gadget"
#define MSG_PENKIND_USSTRINGGADFRONT_STR "FG Unselected string gadget"
#define MSG_PENKIND_SSTRINGGADFRONT_STR "FG Selected string gadget"
#define MSG_COLOR_0_STR "Pen 0"
#define MSG_COLOR_1_STR "Pen 1"
#define MSG_COLOR_2_STR "Pen 2"
#define MSG_COLOR_3_STR "Pen 3"
#define MSG_COLOR_4_STR "Pen 4"
#define MSG_COLOR_5_STR "Pen 5"
#define MSG_COLOR_6_STR "Pen 6"
#define MSG_COLOR_7_STR "Pen 7"
#define MSG_CYCLE_WIDTH_THICK_STR "thick"
#define MSG_CYCLE_WIDTH_THIN_STR "thin"
#define MSG_CYCLE_TITLE_NORMAL_STR "normal"
#define MSG_CYCLE_TITLE_HIGHLIGHT_STR "highlight"
#define MSG_CYCLE_TITLE_SHADOW_STR "shadow"
#define MSG_CYCLE_RAISED_RECESSED_STR "recessed"
#define MSG_CYCLE_RAISED_RAISED_STR "raised"
#define MSG_CYCLE_KIND_STANDARD_STR "Standard"
#define MSG_CYCLE_KIND_STRING_STR "String"
#define MSG_CYCLE_KIND_ICONDROPBOX_STR "Icon drop box"
#define MSG_CYCLE_KIND_XENBUTTON1_STR "XEN button 1"
#define MSG_CYCLE_KIND_XENBUTTON2_STR "XEN button 2"
#define MSG_CYCLE_KIND_NEXTBUTTON_STR "NeXT button"
#define MSG_CYCLE_PENTYPE_SYSTEMPEN_STR "System pen"
#define MSG_CYCLE_PENTYPE_PEN_STR "Pen"
#define MSG_CYCLE_PATTERNTYPE_BFPATTERN_STR "Backfill pattern"
#define MSG_CYCLE_PATTERNTYPE_PEN_STR "Pen"
#define MSG_ERROR_LOADSETTINGS_STR "Can't load settings."
#define MSG_ERROR_CREATEAPP_STR "Can't create application."
#define MSG_ERROR_INSTALLTRITON_STR "Failed to install the Triton Preferences System."
#define MSG_ERROR_MAINWINDOW_STR "Can't open main window."
#define MSG_ERROR_BOOPSIIMAGE_STR "Can't initialize BOOPSI image."
#define MSG_ERROR_NOTRITONLIB_STR "Can't open triton.library version 3 (release 1.2)."
#define MSG_ERROR_NOMEM_STR "Not enough memory."
#define MSG_ERROR_NOREQTOOLSNOASLLIB_STR "You need either reqtools.library or asl.library v38+."
#define MSG_ERROR_CHECKSUM_STR "Invalid application settings file for application\n%%s%s."
#define MSG_TRITON_APP_LONGNAME_STR "Triton Preferences"
#define MSG_TRITON_APP_INFO_STR "The Triton Preferences Editor\n© 1994-1995 by Stefan Zeiger"
#define MSG_UNNAMEDSCREEN_LABEL_STR "(unnamed)"
#define MSG_PRDEFSCREEN_LABEL_STR "«Program default»"
#define MSG_DEFSCREEN_LABEL_STR "«Default»"
#define MSG_WBSCREEN_LABEL_STR "«Workbench»"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
    LONG   cca_ID;
    STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
    {MSG_MAIN_PROJECT_MENU,(STRPTR)MSG_MAIN_PROJECT_MENU_STR},
    {MSG_MAIN_PROJECT_REMOVE,(STRPTR)MSG_MAIN_PROJECT_REMOVE_STR},
    {MSG_MAIN_PROJECT_ABOUT,(STRPTR)MSG_MAIN_PROJECT_ABOUT_STR},
    {MSG_MAIN_PROJECT_QUIT,(STRPTR)MSG_MAIN_PROJECT_QUIT_STR},
    {MSG_MAIN_EDIT_MENU,(STRPTR)MSG_MAIN_EDIT_MENU_STR},
    {MSG_MAIN_EDIT_DEFAULTS,(STRPTR)MSG_MAIN_EDIT_DEFAULTS_STR},
    {MSG_MAIN_EDIT_LASTSAVED,(STRPTR)MSG_MAIN_EDIT_LASTSAVED_STR},
    {MSG_MAIN_EDIT_RESTORE,(STRPTR)MSG_MAIN_EDIT_RESTORE_STR},
    {MSG_MAIN_EDIT_GLOBAL,(STRPTR)MSG_MAIN_EDIT_GLOBAL_STR},
    {MSG_MAIN_APPLICATIONS_GADGET,(STRPTR)MSG_MAIN_APPLICATIONS_GADGET_STR},
    {MSG_MAIN_INFO_GADGET,(STRPTR)MSG_MAIN_INFO_GADGET_STR},
    {MSG_MAIN_DELETE_GADGET,(STRPTR)MSG_MAIN_DELETE_GADGET_STR},
    {MSG_MAIN_FRAMES_GADGET,(STRPTR)MSG_MAIN_FRAMES_GADGET_STR},
    {MSG_MAIN_PENS_GADGET,(STRPTR)MSG_MAIN_PENS_GADGET_STR},
    {MSG_MAIN_IMAGES_GADGET,(STRPTR)MSG_MAIN_IMAGES_GADGET_STR},
    {MSG_MAIN_WINDOWS_GADGET,(STRPTR)MSG_MAIN_WINDOWS_GADGET_STR},
    {MSG_MAIN_SYSTEM_GADGET,(STRPTR)MSG_MAIN_SYSTEM_GADGET_STR},
    {MSG_MAIN_SAVE_GADGET,(STRPTR)MSG_MAIN_SAVE_GADGET_STR},
    {MSG_MAIN_USE_GADGET,(STRPTR)MSG_MAIN_USE_GADGET_STR},
    {MSG_MAIN_TEST_GADGET,(STRPTR)MSG_MAIN_TEST_GADGET_STR},
    {MSG_FRAMES_WIDTH_GADGET,(STRPTR)MSG_FRAMES_WIDTH_GADGET_STR},
    {MSG_FRAMES_TITLE_GADGET,(STRPTR)MSG_FRAMES_TITLE_GADGET_STR},
    {MSG_FRAMES_FRAMETYPES_TEXT,(STRPTR)MSG_FRAMES_FRAMETYPES_TEXT_STR},
    {MSG_FRAMES_KIND_BUTTON_GADGET,(STRPTR)MSG_FRAMES_KIND_BUTTON_GADGET_STR},
    {MSG_FRAMES_KIND_FRAMEBOX_GADGET,(STRPTR)MSG_FRAMES_KIND_FRAMEBOX_GADGET_STR},
    {MSG_FRAMES_KIND_GROUPBOX_GADGET,(STRPTR)MSG_FRAMES_KIND_GROUPBOX_GADGET_STR},
    {MSG_FRAMES_KIND_PROGRESS_GADGET,(STRPTR)MSG_FRAMES_KIND_PROGRESS_GADGET_STR},
    {MSG_FRAMES_KIND_ICONDROPBOX_GADGET,(STRPTR)MSG_FRAMES_KIND_ICONDROPBOX_GADGET_STR},
    {MSG_WINDOWS_WINDOWS_GADGET,(STRPTR)MSG_WINDOWS_WINDOWS_GADGET_STR},
    {MSG_SYSTEM_PUBSCREENS_GADGET,(STRPTR)MSG_SYSTEM_PUBSCREENS_GADGET_STR},
    {MSG_WINDOWS_INFO_GADGET,(STRPTR)MSG_WINDOWS_INFO_GADGET_STR},
    {MSG_WINDOWS_SNAPSHOT_GADGET,(STRPTR)MSG_WINDOWS_SNAPSHOT_GADGET_STR},
    {MSG_WINDOWS_UNSNAPSHOT_GADGET,(STRPTR)MSG_WINDOWS_UNSNAPSHOT_GADGET_STR},
    {MSG_WINDOWS_SNAPSHOTALL_GADGET,(STRPTR)MSG_WINDOWS_SNAPSHOTALL_GADGET_STR},
    {MSG_WINDOWS_UNSNAPSHOTALL_GADGET,(STRPTR)MSG_WINDOWS_UNSNAPSHOTALL_GADGET_STR},
    {MSG_SYSTEM_ADD_GADGET,(STRPTR)MSG_SYSTEM_ADD_GADGET_STR},
    {MSG_SYSTEM_DELETE_GADGET,(STRPTR)MSG_SYSTEM_DELETE_GADGET_STR},
    {MSG_SYSTEM_EDIT_GADGET,(STRPTR)MSG_SYSTEM_EDIT_GADGET_STR},
    {MSG_SYSTEM_TEST_GADGET,(STRPTR)MSG_SYSTEM_TEST_GADGET_STR},
    {MSG_SYSTEM_USE_GADGET,(STRPTR)MSG_SYSTEM_USE_GADGET_STR},
    {MSG_SYSTEM_MISC_LABEL,(STRPTR)MSG_SYSTEM_MISC_LABEL_STR},
    {MSG_SYSTEM_SIMPLEREFRESH_CHECKBOX,(STRPTR)MSG_SYSTEM_SIMPLEREFRESH_CHECKBOX_STR},
    {MSG_SCREEN_INFOLINE,(STRPTR)MSG_SCREEN_INFOLINE_STR},
    {MSG_SCREEN_SCREENMODE_GADGET,(STRPTR)MSG_SCREEN_SCREENMODE_GADGET_STR},
    {MSG_SCREEN_PUBLICNAME_GADGET,(STRPTR)MSG_SCREEN_PUBLICNAME_GADGET_STR},
    {MSG_SCREEN_SCREENTITLE_GADGET,(STRPTR)MSG_SCREEN_SCREENTITLE_GADGET_STR},
    {MSG_PENS_TYPE_GADGET,(STRPTR)MSG_PENS_TYPE_GADGET_STR},
    {MSG_IMAGES_TYPE_GADGET,(STRPTR)MSG_IMAGES_TYPE_GADGET_STR},
    {MSG_IMAGES_RETURN_CHECKBOX,(STRPTR)MSG_IMAGES_RETURN_CHECKBOX_STR},
    {MSG_OK_GAD,(STRPTR)MSG_OK_GAD_STR},
    {MSG_CANCEL_GAD,(STRPTR)MSG_CANCEL_GAD_STR},
    {MSG_YES_NO_GAD,(STRPTR)MSG_YES_NO_GAD_STR},
    {MSG_REMOVEIT_ABORT_GAD,(STRPTR)MSG_REMOVEIT_ABORT_GAD_STR},
    {MSG_INSTALLIT_QUIT_GAD,(STRPTR)MSG_INSTALLIT_QUIT_GAD_STR},
    {MSG_MAIN_TITLE,(STRPTR)MSG_MAIN_TITLE_STR},
    {MSG_FRAMES_TITLE,(STRPTR)MSG_FRAMES_TITLE_STR},
    {MSG_PENS_TITLE,(STRPTR)MSG_PENS_TITLE_STR},
    {MSG_IMAGES_TITLE,(STRPTR)MSG_IMAGES_TITLE_STR},
    {MSG_WINDOWS_TITLE,(STRPTR)MSG_WINDOWS_TITLE_STR},
    {MSG_SYSTEM_TITLE,(STRPTR)MSG_SYSTEM_TITLE_STR},
    {MSG_ERROR_TITLE,(STRPTR)MSG_ERROR_TITLE_STR},
    {MSG_SCREEN_TITLE,(STRPTR)MSG_SCREEN_TITLE_STR},
    {MSG_TESTSCREEN_TITLE,(STRPTR)MSG_TESTSCREEN_TITLE_STR},
    {MSG_APPINFO_TITLE,(STRPTR)MSG_APPINFO_TITLE_STR},
    {MSG_WININFO_TITLE,(STRPTR)MSG_WININFO_TITLE_STR},
    {MSG_ABOUT_TITLE,(STRPTR)MSG_ABOUT_TITLE_STR},
    {MSG_PICKSCREENMODE_TITLE,(STRPTR)MSG_PICKSCREENMODE_TITLE_STR},
    {MSG_APPINFO_REQUESTER,(STRPTR)MSG_APPINFO_REQUESTER_STR},
    {MSG_REMOVE_REQUESTER,(STRPTR)MSG_REMOVE_REQUESTER_STR},
    {MSG_WININFO_REQUESTER,(STRPTR)MSG_WININFO_REQUESTER_STR},
    {MSG_ABOUT_UNREG,(STRPTR)MSG_ABOUT_UNREG_STR},
    {MSG_ABOUT_REG,(STRPTR)MSG_ABOUT_REG_STR},
    {MSG_DELETEAPP_REQUESTER,(STRPTR)MSG_DELETEAPP_REQUESTER_STR},
    {MSG_INSTALLPREFS_REQUESTER,(STRPTR)MSG_INSTALLPREFS_REQUESTER_STR},
    {MSG_GLOBALNAME,(STRPTR)MSG_GLOBALNAME_STR},
    {MSG_SYSTEMPEN_DETAILPEN,(STRPTR)MSG_SYSTEMPEN_DETAILPEN_STR},
    {MSG_SYSTEMPEN_BLOCKPEN,(STRPTR)MSG_SYSTEMPEN_BLOCKPEN_STR},
    {MSG_SYSTEMPEN_TEXTPEN,(STRPTR)MSG_SYSTEMPEN_TEXTPEN_STR},
    {MSG_SYSTEMPEN_SHINEPEN,(STRPTR)MSG_SYSTEMPEN_SHINEPEN_STR},
    {MSG_SYSTEMPEN_SHADOWPEN,(STRPTR)MSG_SYSTEMPEN_SHADOWPEN_STR},
    {MSG_SYSTEMPEN_FILLPEN,(STRPTR)MSG_SYSTEMPEN_FILLPEN_STR},
    {MSG_SYSTEMPEN_FILLTEXTPEN,(STRPTR)MSG_SYSTEMPEN_FILLTEXTPEN_STR},
    {MSG_SYSTEMPEN_BACKGROUNDPEN,(STRPTR)MSG_SYSTEMPEN_BACKGROUNDPEN_STR},
    {MSG_SYSTEMPEN_HIGHLIGHTTEXTPEN,(STRPTR)MSG_SYSTEMPEN_HIGHLIGHTTEXTPEN_STR},
    {MSG_IMAGE_WINBACK,(STRPTR)MSG_IMAGE_WINBACK_STR},
    {MSG_IMAGE_REQBACK,(STRPTR)MSG_IMAGE_REQBACK_STR},
    {MSG_IMAGE_USBUTTONBACK,(STRPTR)MSG_IMAGE_USBUTTONBACK_STR},
    {MSG_IMAGE_SBUTTONBACK,(STRPTR)MSG_IMAGE_SBUTTONBACK_STR},
    {MSG_PATTERN_BACKGROUND,(STRPTR)MSG_PATTERN_BACKGROUND_STR},
    {MSG_PATTERN_SHINE,(STRPTR)MSG_PATTERN_SHINE_STR},
    {MSG_PATTERN_SHINE_SHADOW,(STRPTR)MSG_PATTERN_SHINE_SHADOW_STR},
    {MSG_PATTERN_SHINE_FILL,(STRPTR)MSG_PATTERN_SHINE_FILL_STR},
    {MSG_PATTERN_SHINE_BACKGROUND,(STRPTR)MSG_PATTERN_SHINE_BACKGROUND_STR},
    {MSG_PATTERN_SHADOW,(STRPTR)MSG_PATTERN_SHADOW_STR},
    {MSG_PATTERN_SHADOW_FILL,(STRPTR)MSG_PATTERN_SHADOW_FILL_STR},
    {MSG_PATTERN_SHADOW_BACKGROUND,(STRPTR)MSG_PATTERN_SHADOW_BACKGROUND_STR},
    {MSG_PATTERN_FILL,(STRPTR)MSG_PATTERN_FILL_STR},
    {MSG_PATTERN_FILL_BACKGROUND,(STRPTR)MSG_PATTERN_FILL_BACKGROUND_STR},
    {MSG_PENKIND_NORMUSCORE,(STRPTR)MSG_PENKIND_NORMUSCORE_STR},
    {MSG_PENKIND_HIGHUSCORE,(STRPTR)MSG_PENKIND_HIGHUSCORE_STR},
    {MSG_PENKIND_HALFSHINE,(STRPTR)MSG_PENKIND_HALFSHINE_STR},
    {MSG_PENKIND_HALFSHADOW,(STRPTR)MSG_PENKIND_HALFSHADOW_STR},
    {MSG_PENKIND_USSTRINGGADBACK,(STRPTR)MSG_PENKIND_USSTRINGGADBACK_STR},
    {MSG_PENKIND_SSTRINGGADBACK,(STRPTR)MSG_PENKIND_SSTRINGGADBACK_STR},
    {MSG_PENKIND_USSTRINGGADFRONT,(STRPTR)MSG_PENKIND_USSTRINGGADFRONT_STR},
    {MSG_PENKIND_SSTRINGGADFRONT,(STRPTR)MSG_PENKIND_SSTRINGGADFRONT_STR},
    {MSG_COLOR_0,(STRPTR)MSG_COLOR_0_STR},
    {MSG_COLOR_1,(STRPTR)MSG_COLOR_1_STR},
    {MSG_COLOR_2,(STRPTR)MSG_COLOR_2_STR},
    {MSG_COLOR_3,(STRPTR)MSG_COLOR_3_STR},
    {MSG_COLOR_4,(STRPTR)MSG_COLOR_4_STR},
    {MSG_COLOR_5,(STRPTR)MSG_COLOR_5_STR},
    {MSG_COLOR_6,(STRPTR)MSG_COLOR_6_STR},
    {MSG_COLOR_7,(STRPTR)MSG_COLOR_7_STR},
    {MSG_CYCLE_WIDTH_THICK,(STRPTR)MSG_CYCLE_WIDTH_THICK_STR},
    {MSG_CYCLE_WIDTH_THIN,(STRPTR)MSG_CYCLE_WIDTH_THIN_STR},
    {MSG_CYCLE_TITLE_NORMAL,(STRPTR)MSG_CYCLE_TITLE_NORMAL_STR},
    {MSG_CYCLE_TITLE_HIGHLIGHT,(STRPTR)MSG_CYCLE_TITLE_HIGHLIGHT_STR},
    {MSG_CYCLE_TITLE_SHADOW,(STRPTR)MSG_CYCLE_TITLE_SHADOW_STR},
    {MSG_CYCLE_RAISED_RECESSED,(STRPTR)MSG_CYCLE_RAISED_RECESSED_STR},
    {MSG_CYCLE_RAISED_RAISED,(STRPTR)MSG_CYCLE_RAISED_RAISED_STR},
    {MSG_CYCLE_KIND_STANDARD,(STRPTR)MSG_CYCLE_KIND_STANDARD_STR},
    {MSG_CYCLE_KIND_STRING,(STRPTR)MSG_CYCLE_KIND_STRING_STR},
    {MSG_CYCLE_KIND_ICONDROPBOX,(STRPTR)MSG_CYCLE_KIND_ICONDROPBOX_STR},
    {MSG_CYCLE_KIND_XENBUTTON1,(STRPTR)MSG_CYCLE_KIND_XENBUTTON1_STR},
    {MSG_CYCLE_KIND_XENBUTTON2,(STRPTR)MSG_CYCLE_KIND_XENBUTTON2_STR},
    {MSG_CYCLE_KIND_NEXTBUTTON,(STRPTR)MSG_CYCLE_KIND_NEXTBUTTON_STR},
    {MSG_CYCLE_PENTYPE_SYSTEMPEN,(STRPTR)MSG_CYCLE_PENTYPE_SYSTEMPEN_STR},
    {MSG_CYCLE_PENTYPE_PEN,(STRPTR)MSG_CYCLE_PENTYPE_PEN_STR},
    {MSG_CYCLE_PATTERNTYPE_BFPATTERN,(STRPTR)MSG_CYCLE_PATTERNTYPE_BFPATTERN_STR},
    {MSG_CYCLE_PATTERNTYPE_PEN,(STRPTR)MSG_CYCLE_PATTERNTYPE_PEN_STR},
    {MSG_ERROR_LOADSETTINGS,(STRPTR)MSG_ERROR_LOADSETTINGS_STR},
    {MSG_ERROR_CREATEAPP,(STRPTR)MSG_ERROR_CREATEAPP_STR},
    {MSG_ERROR_INSTALLTRITON,(STRPTR)MSG_ERROR_INSTALLTRITON_STR},
    {MSG_ERROR_MAINWINDOW,(STRPTR)MSG_ERROR_MAINWINDOW_STR},
    {MSG_ERROR_BOOPSIIMAGE,(STRPTR)MSG_ERROR_BOOPSIIMAGE_STR},
    {MSG_ERROR_NOTRITONLIB,(STRPTR)MSG_ERROR_NOTRITONLIB_STR},
    {MSG_ERROR_NOMEM,(STRPTR)MSG_ERROR_NOMEM_STR},
    {MSG_ERROR_NOREQTOOLSNOASLLIB,(STRPTR)MSG_ERROR_NOREQTOOLSNOASLLIB_STR},
    {MSG_ERROR_CHECKSUM,(STRPTR)MSG_ERROR_CHECKSUM_STR},
    {MSG_TRITON_APP_LONGNAME,(STRPTR)MSG_TRITON_APP_LONGNAME_STR},
    {MSG_TRITON_APP_INFO,(STRPTR)MSG_TRITON_APP_INFO_STR},
    {MSG_UNNAMEDSCREEN_LABEL,(STRPTR)MSG_UNNAMEDSCREEN_LABEL_STR},
    {MSG_PRDEFSCREEN_LABEL,(STRPTR)MSG_PRDEFSCREEN_LABEL_STR},
    {MSG_DEFSCREEN_LABEL,(STRPTR)MSG_DEFSCREEN_LABEL_STR},
    {MSG_WBSCREEN_LABEL,(STRPTR)MSG_WBSCREEN_LABEL_STR},
};

#endif /* CATCOMP_ARRAY */


/****************************************************************************/


#ifdef CATCOMP_BLOCK

static const char CatCompBlock[] =
{
    "\x00\x00\x00\x00\x00\x08"
    MSG_MAIN_PROJECT_MENU_STR "\x00"
    "\x00\x00\x00\x01\x00\x0C"
    MSG_MAIN_PROJECT_REMOVE_STR "\x00"
    "\x00\x00\x00\x02\x00\x0C"
    MSG_MAIN_PROJECT_ABOUT_STR "\x00\x00"
    "\x00\x00\x00\x03\x00\x08"
    MSG_MAIN_PROJECT_QUIT_STR "\x00\x00"
    "\x00\x00\x00\x04\x00\x06"
    MSG_MAIN_EDIT_MENU_STR "\x00\x00"
    "\x00\x00\x00\x05\x00\x14"
    MSG_MAIN_EDIT_DEFAULTS_STR "\x00"
    "\x00\x00\x00\x06\x00\x0E"
    MSG_MAIN_EDIT_LASTSAVED_STR "\x00\x00"
    "\x00\x00\x00\x07\x00\x0A"
    MSG_MAIN_EDIT_RESTORE_STR "\x00"
    "\x00\x00\x00\x08\x00\x12"
    MSG_MAIN_EDIT_GLOBAL_STR "\x00"
    "\x00\x00\x00\x09\x00\x0E"
    MSG_MAIN_APPLICATIONS_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x0A\x00\x06"
    MSG_MAIN_INFO_GADGET_STR "\x00"
    "\x00\x00\x00\x0B\x00\x08"
    MSG_MAIN_DELETE_GADGET_STR "\x00"
    "\x00\x00\x00\x0C\x00\x08"
    MSG_MAIN_FRAMES_GADGET_STR "\x00"
    "\x00\x00\x00\x0D\x00\x06"
    MSG_MAIN_PENS_GADGET_STR "\x00"
    "\x00\x00\x00\x0E\x00\x08"
    MSG_MAIN_IMAGES_GADGET_STR "\x00"
    "\x00\x00\x00\x0F\x00\x0A"
    MSG_MAIN_WINDOWS_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x10\x00\x08"
    MSG_MAIN_SYSTEM_GADGET_STR "\x00"
    "\x00\x00\x00\x11\x00\x06"
    MSG_MAIN_SAVE_GADGET_STR "\x00"
    "\x00\x00\x00\x12\x00\x06"
    MSG_MAIN_USE_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x13\x00\x06"
    MSG_MAIN_TEST_GADGET_STR "\x00"
    "\x00\x00\x00\x14\x00\x08"
    MSG_FRAMES_WIDTH_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x15\x00\x08"
    MSG_FRAMES_TITLE_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x16\x00\x0C"
    MSG_FRAMES_FRAMETYPES_TEXT_STR "\x00"
    "\x00\x00\x00\x17\x00\x08"
    MSG_FRAMES_KIND_BUTTON_GADGET_STR "\x00"
    "\x00\x00\x00\x18\x00\x0E"
    MSG_FRAMES_KIND_FRAMEBOX_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x19\x00\x0E"
    MSG_FRAMES_KIND_GROUPBOX_GADGET_STR "\x00"
    "\x00\x00\x00\x1A\x00\x14"
    MSG_FRAMES_KIND_PROGRESS_GADGET_STR "\x00"
    "\x00\x00\x00\x1B\x00\x10"
    MSG_FRAMES_KIND_ICONDROPBOX_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x1C\x00\x08"
    MSG_WINDOWS_WINDOWS_GADGET_STR "\x00"
    "\x00\x00\x00\x1D\x00\x10"
    MSG_SYSTEM_PUBSCREENS_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x1E\x00\x06"
    MSG_WINDOWS_INFO_GADGET_STR "\x00"
    "\x00\x00\x00\x1F\x00\x0A"
    MSG_WINDOWS_SNAPSHOT_GADGET_STR "\x00"
    "\x00\x00\x00\x20\x00\x0C"
    MSG_WINDOWS_UNSNAPSHOT_GADGET_STR "\x00"
    "\x00\x00\x00\x21\x00\x0E"
    MSG_WINDOWS_SNAPSHOTALL_GADGET_STR "\x00"
    "\x00\x00\x00\x22\x00\x10"
    MSG_WINDOWS_UNSNAPSHOTALL_GADGET_STR "\x00"
    "\x00\x00\x00\x23\x00\x06"
    MSG_SYSTEM_ADD_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x24\x00\x08"
    MSG_SYSTEM_DELETE_GADGET_STR "\x00"
    "\x00\x00\x00\x25\x00\x06"
    MSG_SYSTEM_EDIT_GADGET_STR "\x00"
    "\x00\x00\x00\x26\x00\x06"
    MSG_SYSTEM_TEST_GADGET_STR "\x00"
    "\x00\x00\x00\x27\x00\x06"
    MSG_SYSTEM_USE_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x28\x00\x0E"
    MSG_SYSTEM_MISC_LABEL_STR "\x00"
    "\x00\x00\x00\x29\x00\x10"
    MSG_SYSTEM_SIMPLEREFRESH_CHECKBOX_STR "\x00"
    "\x00\x00\x00\x2A\x00\x10"
    MSG_SCREEN_INFOLINE_STR "\x00\x00"
    "\x00\x00\x00\x2B\x00\x0E"
    MSG_SCREEN_SCREENMODE_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x2C\x00\x0E"
    MSG_SCREEN_PUBLICNAME_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x2D\x00\x0E"
    MSG_SCREEN_SCREENTITLE_GADGET_STR "\x00"
    "\x00\x00\x00\x2E\x00\x08"
    MSG_PENS_TYPE_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x2F\x00\x08"
    MSG_IMAGES_TYPE_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x30\x00\x20"
    MSG_IMAGES_RETURN_CHECKBOX_STR "\x00\x00"
    "\x00\x00\x00\x31\x00\x04"
    MSG_OK_GAD_STR "\x00"
    "\x00\x00\x00\x32\x00\x08"
    MSG_CANCEL_GAD_STR "\x00"
    "\x00\x00\x00\x33\x00\x0A"
    MSG_YES_NO_GAD_STR "\x00\x00"
    "\x00\x00\x00\x34\x00\x12"
    MSG_REMOVEIT_ABORT_GAD_STR "\x00"
    "\x00\x00\x00\x35\x00\x12"
    MSG_INSTALLIT_QUIT_GAD_STR "\x00"
    "\x00\x00\x00\x36\x00\x14"
    MSG_MAIN_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x37\x00\x08"
    MSG_FRAMES_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x38\x00\x06"
    MSG_PENS_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x39\x00\x08"
    MSG_IMAGES_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x3A\x00\x08"
    MSG_WINDOWS_TITLE_STR "\x00"
    "\x00\x00\x00\x3B\x00\x08"
    MSG_SYSTEM_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x3C\x00\x06"
    MSG_ERROR_TITLE_STR "\x00"
    "\x00\x00\x00\x3D\x00\x14"
    MSG_SCREEN_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x3E\x00\x1A"
    MSG_TESTSCREEN_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x3F\x00\x12"
    MSG_APPINFO_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x40\x00\x0C"
    MSG_WININFO_TITLE_STR "\x00"
    "\x00\x00\x00\x41\x00\x0A"
    MSG_ABOUT_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x42\x00\x14"
    MSG_PICKSCREENMODE_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x43\x00\x58"
    MSG_APPINFO_REQUESTER_STR "\x00"
    "\x00\x00\x00\x44\x01\x16"
    MSG_REMOVE_REQUESTER_STR "\x00"
    "\x00\x00\x00\x45\x00\x6C"
    MSG_WININFO_REQUESTER_STR "\x00\x00"
    "\x00\x00\x00\x46\x01\x10"
    MSG_ABOUT_UNREG_STR "\x00"
    "\x00\x00\x00\x47\x00\xA8"
    MSG_ABOUT_REG_STR "\x00"
    "\x00\x00\x00\x48\x00\x60"
    MSG_DELETEAPP_REQUESTER_STR "\x00"
    "\x00\x00\x00\x49\x01\x14"
    MSG_INSTALLPREFS_REQUESTER_STR "\x00"
    "\x00\x00\x00\x4A\x00\x0A"
    MSG_GLOBALNAME_STR "\x00\x00"
    "\x00\x00\x00\x4B\x00\x0C"
    MSG_SYSTEMPEN_DETAILPEN_STR "\x00\x00"
    "\x00\x00\x00\x4C\x00\x0A"
    MSG_SYSTEMPEN_BLOCKPEN_STR "\x00"
    "\x00\x00\x00\x4D\x00\x0A"
    MSG_SYSTEMPEN_TEXTPEN_STR "\x00\x00"
    "\x00\x00\x00\x4E\x00\x0A"
    MSG_SYSTEMPEN_SHINEPEN_STR "\x00"
    "\x00\x00\x00\x4F\x00\x0C"
    MSG_SYSTEMPEN_SHADOWPEN_STR "\x00\x00"
    "\x00\x00\x00\x50\x00\x0A"
    MSG_SYSTEMPEN_FILLPEN_STR "\x00\x00"
    "\x00\x00\x00\x51\x00\x0E"
    MSG_SYSTEMPEN_FILLTEXTPEN_STR "\x00"
    "\x00\x00\x00\x52\x00\x10"
    MSG_SYSTEMPEN_BACKGROUNDPEN_STR "\x00\x00"
    "\x00\x00\x00\x53\x00\x14"
    MSG_SYSTEMPEN_HIGHLIGHTTEXTPEN_STR "\x00\x00"
    "\x00\x00\x00\x54\x00\x0A"
    MSG_IMAGE_WINBACK_STR "\x00"
    "\x00\x00\x00\x55\x00\x0E"
    MSG_IMAGE_REQBACK_STR "\x00\x00"
    "\x00\x00\x00\x56\x00\x16"
    MSG_IMAGE_USBUTTONBACK_STR "\x00\x00"
    "\x00\x00\x00\x57\x00\x14"
    MSG_IMAGE_SBUTTONBACK_STR "\x00\x00"
    "\x00\x00\x00\x58\x00\x0C"
    MSG_PATTERN_BACKGROUND_STR "\x00\x00"
    "\x00\x00\x00\x59\x00\x06"
    MSG_PATTERN_SHINE_STR "\x00"
    "\x00\x00\x00\x5A\x00\x0E"
    MSG_PATTERN_SHINE_SHADOW_STR "\x00\x00"
    "\x00\x00\x00\x5B\x00\x0C"
    MSG_PATTERN_SHINE_FILL_STR "\x00\x00"
    "\x00\x00\x00\x5C\x00\x12"
    MSG_PATTERN_SHINE_BACKGROUND_STR "\x00\x00"
    "\x00\x00\x00\x5D\x00\x08"
    MSG_PATTERN_SHADOW_STR "\x00\x00"
    "\x00\x00\x00\x5E\x00\x0C"
    MSG_PATTERN_SHADOW_FILL_STR "\x00"
    "\x00\x00\x00\x5F\x00\x12"
    MSG_PATTERN_SHADOW_BACKGROUND_STR "\x00"
    "\x00\x00\x00\x60\x00\x06"
    MSG_PATTERN_FILL_STR "\x00\x00"
    "\x00\x00\x00\x61\x00\x10"
    MSG_PATTERN_FILL_BACKGROUND_STR "\x00"
    "\x00\x00\x00\x62\x00\x0C"
    MSG_PENKIND_NORMUSCORE_STR "\x00\x00"
    "\x00\x00\x00\x63\x00\x18"
    MSG_PENKIND_HIGHUSCORE_STR "\x00\x00"
    "\x00\x00\x00\x64\x00\x0A"
    MSG_PENKIND_HALFSHINE_STR "\x00"
    "\x00\x00\x00\x65\x00\x0C"
    MSG_PENKIND_HALFSHADOW_STR "\x00\x00"
    "\x00\x00\x00\x66\x00\x1C"
    MSG_PENKIND_USSTRINGGADBACK_STR "\x00"
    "\x00\x00\x00\x67\x00\x1A"
    MSG_PENKIND_SSTRINGGADBACK_STR "\x00"
    "\x00\x00\x00\x68\x00\x1C"
    MSG_PENKIND_USSTRINGGADFRONT_STR "\x00"
    "\x00\x00\x00\x69\x00\x1A"
    MSG_PENKIND_SSTRINGGADFRONT_STR "\x00"
    "\x00\x00\x00\x6A\x00\x06"
    MSG_COLOR_0_STR "\x00"
    "\x00\x00\x00\x6B\x00\x06"
    MSG_COLOR_1_STR "\x00"
    "\x00\x00\x00\x6C\x00\x06"
    MSG_COLOR_2_STR "\x00"
    "\x00\x00\x00\x6D\x00\x06"
    MSG_COLOR_3_STR "\x00"
    "\x00\x00\x00\x6E\x00\x06"
    MSG_COLOR_4_STR "\x00"
    "\x00\x00\x00\x6F\x00\x06"
    MSG_COLOR_5_STR "\x00"
    "\x00\x00\x00\x70\x00\x06"
    MSG_COLOR_6_STR "\x00"
    "\x00\x00\x00\x71\x00\x06"
    MSG_COLOR_7_STR "\x00"
    "\x00\x00\x00\x72\x00\x06"
    MSG_CYCLE_WIDTH_THICK_STR "\x00"
    "\x00\x00\x00\x73\x00\x06"
    MSG_CYCLE_WIDTH_THIN_STR "\x00\x00"
    "\x00\x00\x00\x74\x00\x08"
    MSG_CYCLE_TITLE_NORMAL_STR "\x00\x00"
    "\x00\x00\x00\x75\x00\x0A"
    MSG_CYCLE_TITLE_HIGHLIGHT_STR "\x00"
    "\x00\x00\x00\x76\x00\x08"
    MSG_CYCLE_TITLE_SHADOW_STR "\x00\x00"
    "\x00\x00\x00\x77\x00\x0A"
    MSG_CYCLE_RAISED_RECESSED_STR "\x00\x00"
    "\x00\x00\x00\x78\x00\x08"
    MSG_CYCLE_RAISED_RAISED_STR "\x00\x00"
    "\x00\x00\x00\x79\x00\x0A"
    MSG_CYCLE_KIND_STANDARD_STR "\x00\x00"
    "\x00\x00\x00\x7A\x00\x08"
    MSG_CYCLE_KIND_STRING_STR "\x00\x00"
    "\x00\x00\x00\x7B\x00\x0E"
    MSG_CYCLE_KIND_ICONDROPBOX_STR "\x00"
    "\x00\x00\x00\x7C\x00\x0E"
    MSG_CYCLE_KIND_XENBUTTON1_STR "\x00\x00"
    "\x00\x00\x00\x7D\x00\x0E"
    MSG_CYCLE_KIND_XENBUTTON2_STR "\x00\x00"
    "\x00\x00\x00\x7E\x00\x0C"
    MSG_CYCLE_KIND_NEXTBUTTON_STR "\x00"
    "\x00\x00\x00\x7F\x00\x0C"
    MSG_CYCLE_PENTYPE_SYSTEMPEN_STR "\x00\x00"
    "\x00\x00\x00\x80\x00\x04"
    MSG_CYCLE_PENTYPE_PEN_STR "\x00"
    "\x00\x00\x00\x81\x00\x12"
    MSG_CYCLE_PATTERNTYPE_BFPATTERN_STR "\x00\x00"
    "\x00\x00\x00\x82\x00\x04"
    MSG_CYCLE_PATTERNTYPE_PEN_STR "\x00"
    "\x00\x00\x00\x83\x00\x16"
    MSG_ERROR_LOADSETTINGS_STR "\x00\x00"
    "\x00\x00\x00\x84\x00\x1A"
    MSG_ERROR_CREATEAPP_STR "\x00"
    "\x00\x00\x00\x85\x00\x32"
    MSG_ERROR_INSTALLTRITON_STR "\x00\x00"
    "\x00\x00\x00\x86\x00\x18"
    MSG_ERROR_MAINWINDOW_STR "\x00"
    "\x00\x00\x00\x87\x00\x20"
    MSG_ERROR_BOOPSIIMAGE_STR "\x00\x00"
    "\x00\x00\x00\x88\x00\x34"
    MSG_ERROR_NOTRITONLIB_STR "\x00\x00"
    "\x00\x00\x00\x89\x00\x14"
    MSG_ERROR_NOMEM_STR "\x00\x00"
    "\x00\x00\x00\x8A\x00\x36"
    MSG_ERROR_NOREQTOOLSNOASLLIB_STR "\x00"
    "\x00\x00\x00\x8B\x00\x3A"
    MSG_ERROR_CHECKSUM_STR "\x00\x00"
    "\x00\x00\x00\x8C\x00\x14"
    MSG_TRITON_APP_LONGNAME_STR "\x00\x00"
    "\x00\x00\x00\x8D\x00\x3C"
    MSG_TRITON_APP_INFO_STR "\x00\x00"
    "\x00\x00\x00\x8E\x00\x0A"
    MSG_UNNAMEDSCREEN_LABEL_STR "\x00"
    "\x00\x00\x00\x8F\x00\x12"
    MSG_PRDEFSCREEN_LABEL_STR "\x00"
    "\x00\x00\x00\x90\x00\x0A"
    MSG_DEFSCREEN_LABEL_STR "\x00"
    "\x00\x00\x00\x91\x00\x0C"
    MSG_WBSCREEN_LABEL_STR "\x00"
};

#endif /* CATCOMP_BLOCK */


/****************************************************************************/


struct LocaleInfo
{
    APTR li_LocaleBase;
    APTR li_Catalog;
};


#include <dos.h>
STRPTR __asm GetString(register __a0 struct LocaleInfo *li,register __d0 ULONG id);


#ifdef CATCOMP_CODE

STRPTR GetString(struct LocaleInfo *li, LONG stringNum)
{
LONG   *l;
UWORD  *w;
STRPTR  builtIn;

    l = (LONG *)CatCompBlock;

    while (*l != stringNum)
    {
        w = (UWORD *)((ULONG)l + 4);
        l = (LONG *)((ULONG)l + (ULONG)*w + 6);
    }
    builtIn = (STRPTR)((ULONG)l + 6);

#define XLocaleBase LocaleBase
#define LocaleBase li->li_LocaleBase
    
    if (LocaleBase)
        return(GetCatalogStr(li->li_Catalog,stringNum,builtIn));
#define LocaleBase XLocaleBase
#undef XLocaleBase

    return(builtIn);
}


#endif /* CATCOMP_CODE */


/****************************************************************************/


#endif /* CATALOGS_TRITONPREFS_H */
