#ifndef PROTO_TRITON_LIB_SFD_H
#define PROTO_TRITON_LIB_SFD_H

/*
** 'C' prototype and compiler specific header file combo
**
** Copyright 1993-1998 by OpenTriton Project
** Changes in 6.115 by amigazen project
** Refactoring for NDK3.2 by amigazen project
** This library is freely distributable under GPL terms.
** This is the OpenTriton 2.0 release of the "triton.library" user
** interface creation and management tool kit.
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/triton_lib.sfd_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * TritonBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_TRITON_LIB_SFD_PRAGMAS_H
#include <pragmas/triton_lib.sfd_pragmas.h>
#endif /* PRAGMAS_TRITON_LIB_SFD_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_TRITON_LIB_SFD_LIB_H
#include <pragma/triton_lib.sfd_lib.h>
#endif /* PRAGMA_TRITON_LIB_SFD_LIB_H */

#elif defined(__VBCC__)

#include <clib/triton_lib.sfd_protos.h>

#ifndef INLINE_TRITON_LIB_SFD_PROTOS_H
#include <inline/triton_lib.sfd_protos.h>
#endif /* INLINE_TRITON_LIB_SFD_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_TRITON_LIB_SFD_H
#include <inline/triton_lib.sfd.h>
#endif /* INLINE_TRITON_LIB_SFD_H */
#else
#include <clib/triton_lib.sfd_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/triton_lib.sfd_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_TRITON_LIB_SFD_H */
